### ISSUE TITLE
能不能把高级传输器【抓取】删除啊

### ISSUE THREAD

**Issue by aprosthesis** [ytdd9527/NetworksExpansion#147]
### Checklist

- [X] You have searched the [list of known issues](https://github.com/ytdd9527/NetworksExpansion/issues) and have not found the same suggestion

### Issue Description

能不能把高级传输器【抓取】删除啊，不能连续抓取，想合成plus版本的，会因为摆错底座合成这玩意纯恶心人

**Comment by balugaq** [comment]
这不能成为删除这个机器的理由
