### ISSUE TITLE
Slimefun Machine builder wand

### ISSUE THREAD

**Issue by Skyfatori** [ytdd9527/NetworksExpansion#98]
### Checklist

- [X] You have searched the [list of known issues](https://github.com/ytdd9527/NetworksExpansion/issues) and have not found the same suggestion

### Reason for Suggestion

Make a builder wand that could be used to place slimefun machine faster.

### Suggestion Details

1

### Additional Information

1

**Comment by balugaq** [comment]
uh.. Isn't it already existing?

**Comment by balugaq** [comment]
Never let players place machines faster, This will cause the server to die faster.
I will close it in 1 day
